# Generated by Django 4.2.7 on 2024-01-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("whatsguard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="ignore",
            field=models.BooleanField(default=False, verbose_name="ignore"),
        ),
    ]
