<<<<<<< HEAD
# Generated by Django 3.1.5 on 2021-01-24 08:07
=======
# Generated by Django 3.1.4 on 2021-01-18 13:56
>>>>>>> 0589f45200456000b660104ddbd72274b5c20252

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Profile',
=======
            name='UserProfile',
>>>>>>> 0589f45200456000b660104ddbd72274b5c20252
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
