# Generated by Django 3.1.4 on 2021-02-23 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='', upload_to='profile_pics')),
                ('major', models.CharField(default='', max_length=25)),
                ('year', models.CharField(blank=True, choices=[('OR', 'Orea'), ('FR', 'Jabal Orea'), ('SP', 'Major Orea'), ('SN', 'Training Orea'), ('JN', 'Dieing Orea')], max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
