# Generated by Django 3.1.7 on 2021-04-08 08:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/ammar-faifi/image/upload/v1617785115/blank_profile_jiosa2.png', max_length=255, verbose_name='image'),
        ),
    ]
