# Generated by Django 3.1.4 on 2021-02-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.CharField(blank=True, choices=[('OR', 'Orea'), ('FR', 'Freshman')], max_length=25),
        ),
    ]
