# Generated by Django 3.1.7 on 2021-02-26 14:43

import account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=account.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/ammar-faifi/image/upload/v1614314169/sample.jpg', max_length=255, verbose_name='image'),
        ),
    ]
