# Generated by Django 3.1.4 on 2021-02-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, height_field=50, upload_to='profile_pics', width_field=50),
        ),
    ]
