# Generated by Django 3.1.4 on 2021-02-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210202_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year',
            field=models.CharField(blank=True, choices=[('OR', 'Orea'), ('FR', 'Jabal Orea'), ('SP', 'Major Orea'), ('SN', 'Training Orea'), ('JN', 'Dieing Orea')], max_length=25),
        ),
    ]
