# Generated by Django 3.1.7 on 2021-02-27 05:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/ammar-faifi/image/upload/v1614377885/icon.jpg', max_length=255, verbose_name='image'),
        ),
    ]
