# Generated by Django 3.1.4 on 2021-02-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210204_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='major',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
