# Generated by Django 3.2.10 on 2022-01-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210614_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(default='en-US', max_length=10, verbose_name='language'),
        ),
    ]
