# Generated by Django 3.2.10 on 2022-01-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_profile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(default='en-US', max_length=10, verbose_name='language'),
        ),
    ]
