# Generated by Django 3.2.10 on 2022-06-08 17:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20220116_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/petroly-initiative/image/upload/v1622359053/profile_pics/blank_profile', max_length=255, verbose_name='profile picture'),
        ),
    ]
