# Generated by Django 4.2.7 on 2023-11-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0013_userlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="premium",
            field=models.BooleanField(default=False, verbose_name="premium"),
        ),
    ]
