# Generated by Django 3.2.5 on 2021-11-29 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('description', models.TextField(max_length=500, verbose_name='وصف')),
                ('link', models.URLField(verbose_name='Link')),
                ('platform', models.CharField(choices=[('whatsapp', 'Whatsapp'), ('discord', 'Discord'), ('telegram', 'Telegram')], max_length=12, verbose_name='Platform')),
                ('category', models.CharField(choices=[('edu', 'Educational'), ('section', 'Section'), ('entertaining', 'Entertaining')], max_length=12, verbose_name='Category')),
                ('likes', models.IntegerField(default=0, verbose_name='likes')),
                ('section', models.CharField(default='', max_length=10, verbose_name='Section')),
                ('report', models.IntegerField(default=0, verbose_name='Report')),
                ('verified', models.BooleanField(default=True, verbose_name='Verified')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
        ),
    ]
