# Generated by Django 3.2.5 on 2021-11-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
    ]
