# Generated by Django 3.2.5 on 2022-01-06 00:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_community_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
    ]
