# Generated by Django 3.2.10 on 2022-01-08 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0003_community_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='user',
        ),
        migrations.AddField(
            model_name='community',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_communities', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Description'),
        ),
        migrations.RemoveField(
            model_name='community',
            name='likes',
        ),
        migrations.AddField(
            model_name='community',
            name='likes',
            field=models.ManyToManyField(default=None, related_name='liked_communities', to=settings.AUTH_USER_MODEL, verbose_name='likes'),
        ),
    ]
