# Generated by Django 3.2.10 on 2022-01-08 06:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0004_auto_20220108_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked_communities', to=settings.AUTH_USER_MODEL, verbose_name='likes'),
        ),
    ]
