# Generated by Django 3.2.4 on 2022-01-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_alter_community_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='section',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Section'),
        ),
    ]
