# Generated by Django 3.2.10 on 2022-01-10 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0006_alter_community_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_communities', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
    ]
