# Generated by Django 3.2.10 on 2022-01-15 10:06

import communities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0009_auto_20220110_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='icon',
            field=communities.models.CloudinaryFieldCostom(blank=True, default=None, max_length=255, null=True, verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Description'),
        ),
    ]
