# Generated by Django 3.2.10 on 2022-01-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0010_auto_20220115_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name': 'community', 'verbose_name_plural': 'Communities'},
        ),
        migrations.AlterField(
            model_name='community',
            name='link',
            field=models.URLField(unique=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
