# Generated by Django 4.0.6 on 2022-07-08 10:28

import communities.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_choices_field.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0011_auto_20220116_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='reports',
        ),
        migrations.AlterField(
            model_name='community',
            name='category',
            field=django_choices_field.fields.TextChoicesField(choices=[('edu', 'Educational'), ('section', 'Section'), ('entertaining', 'Entertaining')], choices_enum=communities.models.Community.CategoryEnum, default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='community',
            name='platform',
            field=django_choices_field.fields.TextChoicesField(choices=[('whatsapp', 'Whatsapp'), ('discord', 'Discord'), ('telegram', 'Telegram')], choices_enum=communities.models.Community.PlatformEnum, default='', max_length=8),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='Created on')),
                ('reason', django_choices_field.fields.TextChoicesField(choices=[('content', 'inappropriate content'), ('link', 'invalid link'), ('other', 'other')], choices_enum=communities.models.Report.ReasonEnum, max_length=7)),
                ('other_reason', models.CharField(blank=True, default='', max_length=100, verbose_name='Other_reason')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='communities.community', verbose_name='community')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
