# Generated by Django 3.2.5 on 2022-01-19 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('communities', '0011_auto_20220116_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='reports',
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('reporter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('reason', models.CharField(choices=[('content', 'Content'), ('link', 'invalidLink'), ('other', 'other')], max_length=8, verbose_name='Reason')),
                ('other_reason', models.CharField(blank=True, default='', max_length=10, verbose_name='Other_reason')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='communities.community', verbose_name='community')),
            ],
        ),
    ]
