# Generated by Django 3.2.5 on 2022-01-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0013_auto_20220119_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='other_reason',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Other_reason'),
        ),
    ]
