# Generated by Django 3.2.5 on 2022-01-19 09:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0014_alter_report_other_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='reporter',
        ),
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.ManyToManyField(blank=True, related_name='reported_communities', to=settings.AUTH_USER_MODEL, verbose_name='reports'),
        ),
    ]
