# Generated by Django 3.2.10 on 2022-01-19 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0015_auto_20220119_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created on'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('content', 'inappropriate content'), ('link', 'invalid link'), ('other', 'other')], max_length=8, verbose_name='Reason'),
        ),
        migrations.RemoveField(
            model_name='report',
            name='reporter',
        ),
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
