# Generated by Django 3.2.10 on 2022-01-19 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0016_auto_20220119_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created on'),
            preserve_default=False,
        ),
    ]
