# Generated by Django 3.2.10 on 2022-01-19 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0016_auto_20220119_1836'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
