# Generated by Django 4.0.5 on 2022-06-17 12:20

import communities.models
from django.db import migrations
import django_choices_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0018_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='category',
            field=django_choices_field.fields.TextChoicesField(choices=[('edu', 'Educational'), ('section', 'Section'), ('entertaining', 'Entertaining')], choices_enum=communities.models.Community.CategoryEnum, default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='community',
            name='platform',
            field=django_choices_field.fields.TextChoicesField(choices=[('whatsapp', 'Whatsapp'), ('discord', 'Discord'), ('telegram', 'Telegram')], choices_enum=communities.models.Community.PlatformEnum, default='', max_length=8),
        ),
    ]
