# Generated by Django 4.0.5 on 2022-06-17 17:21

import communities.models
from django.db import migrations
import django_choices_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0019_alter_community_category_alter_community_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=django_choices_field.fields.TextChoicesField(choices=[('content', 'inappropriate content'), ('link', 'invalid link'), ('other', 'other')], choices_enum=communities.models.Report.ReasonEnum, max_length=7),
        ),
    ]
