# Generated by Django 4.0.5 on 2022-06-24 16:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0020_alter_report_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='icon',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='icon'),
        ),
    ]
