# Generated by Django 4.0.5 on 2022-06-25 15:31

import communities.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0021_alter_community_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='icon',
            field=communities.models.CloudinaryFieldCostom(blank=True, default=None, max_length=255, null=True, verbose_name='icon'),
        ),
    ]
