years = [
	("OR", "Orientation"),
	("FR", "Freshman"),
	("SP", "Sophomore"),
	("JN", "Junior"),
	("SN", "Senior"),
]

departments = [
	("ACFN", "Accounting & Finance"),
	("AE", "Aerospace Engineering"),
	("ARE", "Architectural Engineering"),
	("ARC", "Architecture"),
	("CE", "Civil & Environmental Engg"),
	("CEM", "Construction Engg & Management"),
	("CHE", "Chemical Engineering"),
	("CHEM", "Chemistry"),
	("COE", "Computer Engineering"),
	("CPG", "CPG"),
	("CRP", "City & Regional Planning"),
	("ERTH", "Earth Sciences"),
	("EE", "Electrical Engineering"),
	("ELI", "English Language Inst. (Prep)"),
	("ELD", "English Language Department"),
	("ISOM", "Info. Systems & Operations Mgt"),
	("GS", "Global & Social Studies"),
	("IAS", "Islamic & Arabic Studies"),
	("ICS", "Information & Computer Science"),
	("LS", "Life Sciences"),
	("MATH", "Mathematics & Statistics"),
	("MBA", "Business Administration"),
	("ME", "Mechanical Engineering"),
	("MGT", "Management & Marketing"),
	("PE", "Physical Education"),
	("PETE", "Petroleum Engineering"),
	("PHYS", "Physics"),
	("PSE", "Prep Science & Engineering"),
	("SE", "Systems Engineering"),
]