# fly.toml app configuration file generated for petroly-django on 2024-01-04T19:49:00+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "petroly-django"
primary_region = "cdg"
console_command = "/code/manage.py shell"

[build]

[deploy]
  release_command = "python manage.py migrate --noinput"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
