# Generated by Django 3.1.7 on 2021-04-02 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone Number')),
                ('smoking', models.BooleanField(verbose_name='Do You Smoke')),
                ('staying_up', models.BooleanField(verbose_name='Do Stay Up Late')),
                ('temperature', models.IntegerField(verbose_name='Room Temperature You Like')),
                ('region', models.CharField(max_length=50, verbose_name='Your Hometown')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bid',
                'verbose_name_plural': 'bids',
            },
        ),
    ]
