# Generated by Django 3.1.7 on 2021-04-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommate', '0002_bid_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'verbose_name': 'offer', 'verbose_name_plural': 'offers'},
        ),
        migrations.AlterField(
            model_name='bid',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Personal Email'),
        ),
    ]
