# Generated by Django 3.1.7 on 2021-04-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommate', '0002_auto_20210402_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Your Hometown'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='temperature',
            field=models.IntegerField(blank=True, null=True, verbose_name='Room Temperature You Like'),
        ),
    ]
