# Generated by Django 3.1.7 on 2021-04-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommate', '0003_auto_20210402_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone Number'),
        ),
    ]
