# Generated by Django 3.2.2 on 2021-06-18 18:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roommate', '0003_auto_20210408_0829'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bid',
            new_name='Offer',
        ),
    ]
