# Generated by Django 3.1.7 on 2021-04-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommate', '0005_auto_20210402_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='comment',
            field=models.CharField(blank=True, default='No Comment', max_length=500, null=True, verbose_name='Comment'),
        ),
    ]
