# Generated by Django 3.1.7 on 2021-04-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommate', '0008_remove_bid_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='comment',
            field=models.TextField(blank=True, default='No Comment', verbose_name='Comment'),
        ),
    ]
