# Generated by Django 3.1.7 on 2021-04-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommate', '0009_bid_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='temperature',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Room Temperature You Like'),
        ),
    ]
