# Generated by Django 4.0.6 on 2022-07-13 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_choices_field.fields
import notifier.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('crn', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='CRN')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', django_choices_field.fields.TextChoicesField(choices=[('sms', 'sms'), ('push', 'push'), ('email', 'email'), ('whatsapp', 'whatsapp'), ('telegram', 'telegram')], choices_enum=notifier.models.NotificationChannel.ChannelEnum, max_length=15, verbose_name='channel')),
            ],
            options={
                'verbose_name': 'notification channel',
                'verbose_name_plural': 'notification channels',
            },
        ),
        migrations.CreateModel(
            name='TrackingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channels', models.ManyToManyField(to='notifier.notificationchannel', verbose_name='channels')),
                ('courses', models.ManyToManyField(related_name='tracked_courses', to='notifier.course', verbose_name='courses')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_list', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(blank=True, default=True, verbose_name='success')),
                ('sent_on', models.DateTimeField(auto_now_add=True, verbose_name='sent on')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifier.notificationchannel', verbose_name='channel')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifier.course', verbose_name='course')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
