# Generated by Django 4.0.6 on 2022-07-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long', models.CharField(max_length=10, verbose_name='long')),
                ('short', models.CharField(max_length=5, verbose_name='short')),
                ('allowed', models.BooleanField(verbose_name='allowed')),
            ],
            options={
                'verbose_name': 'term',
                'verbose_name_plural': 'terms',
            },
        ),
    ]
