# Generated by Django 4.0.6 on 2022-08-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='raw_info',
            field=models.JSONField(default=None, null=True, verbose_name='raw info'),
        ),
    ]
