# Generated by Django 4.0.6 on 2022-07-14 05:17

import data
from django.db import migrations
import django_choices_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=django_choices_field.fields.TextChoicesField(choices=[('AF', 'Accounting & Finance'), ('AE', 'Aerospace Engineering'), ('ARE', 'Architectural Engineering'), ('ARC', 'Architecture'), ('CE', 'Civil & Environmental Engg'), ('CEM', 'Construction Engg & Management'), ('CHE', 'Chemical Engineering'), ('CHEM', 'Chemistry'), ('COE', 'Computer Engineering'), ('CPG', 'CPG'), ('CRP', 'City & Regional Planning'), ('ERTH', 'Earth Sciences'), ('EE', 'Electrical Engineering'), ('ELI', 'English Language Inst. (Prep)'), ('ELD', 'English Language Department'), ('FIN', 'Finance'), ('ISOM', 'Info. Systems & Operations Mgt'), ('GS', 'Global & Social Studies'), ('IAS', 'Islamic & Arabic Studies'), ('ICS', 'Information & Computer Science'), ('LS', 'Life Sciences'), ('MATH', 'Mathematics & Statistics'), ('MBA', 'Business Administration'), ('ME', 'Mechanical Engineering'), ('MGT', 'Management & Marketing'), ('PE', 'Physical Education'), ('PETE', 'Petroleum Engineering'), ('PHYS', 'Physics'), ('PSE', 'Prep Science & Engineering'), ('SE', 'Systems Engineering')], choices_enum=data.DepartmentEnum, max_length=4, verbose_name='department'),
        ),
    ]
