# Generated by Django 4.0.6 on 2022-07-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinglist',
            name='courses',
            field=models.ManyToManyField(related_name='tracked_courses', to='notifier.course', verbose_name='courses'),
        ),
    ]
