# Generated by Django 4.0.6 on 2022-08-04 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0002_course_raw_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='raw_info',
            new_name='raw',
        ),
    ]
