# Generated by Django 4.0.6 on 2022-07-12 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifier', '0002_alter_trackinglist_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinglist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_list', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
