# Generated by Django 4.0.6 on 2022-08-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0004_cache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cache',
            name='age',
            field=models.IntegerField(default=30, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='cache',
            name='swr',
            field=models.IntegerField(default=60, verbose_name='swr'),
        ),
    ]
