# Generated by Django 4.0.6 on 2022-08-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0007_alter_cache_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cache',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='updated on'),
        ),
    ]
