# Generated by Django 4.0.6 on 2022-08-20 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0008_alter_cache_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cache',
            name='age',
        ),
        migrations.RemoveField(
            model_name='cache',
            name='swr',
        ),
    ]
