# Generated by Django 4.0.6 on 2022-08-24 17:41

from django.db import migrations, models
import notifier.models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0011_alter_status_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cache',
            name='data',
            field=models.JSONField(default=notifier.models.Cache.data_default, verbose_name='data'),
        ),
    ]
