# Generated by Django 4.1.5 on 2023-01-10 08:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("notifier", "0014_alter_course_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackinglist",
            name="updated_on",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="updated on",
            ),
            preserve_default=False,
        ),
    ]
