# Generated by Django 4.1.7 on 2023-03-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifier", "0015_trackinglist_updated_on"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(
                models.F("crn"), models.F("term"), name="unique_crn_term"
            ),
        ),
    ]
