# Generated by Django 4.1.7 on 2023-03-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifier", "0016_course_unique_crn_term"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="crn",
            field=models.CharField(max_length=5, verbose_name="CRN"),
        ),
    ]
