# Generated by Django 4.2.6 on 2023-11-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifier", "0017_alter_course_crn"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackinglist",
            name="register_courses",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="register_courses",
                to="notifier.course",
                verbose_name="register courses",
            ),
        ),
    ]
