# Generated by Django 4.2.6 on 2023-11-04 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("django_q", "0014_schedule_cluster"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifier", "0018_trackinglist_register_courses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackinglist",
            name="updated_on",
            field=models.DateTimeField(auto_now=True, verbose_name="updated on"),
        ),
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="created on"),
                ),
                (
                    "updated_on",
                    models.DateTimeField(auto_now=True, verbose_name="updated on"),
                ),
                ("cookies", models.JSONField(verbose_name="cookies")),
                (
                    "scheduler",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_q.schedule",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "banner",
                "verbose_name_plural": "banners",
            },
        ),
    ]
