# Generated by Django 4.2.6 on 2023-11-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifier", "0019_alter_trackinglist_updated_on_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="cookies",
            field=models.JSONField(default=None, null=True, verbose_name="cookies"),
        ),
    ]
