# Generated by Django 4.2.7 on 2023-11-26 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("notifier", "0020_alter_banner_cookies"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="active",
            field=models.BooleanField(default=False, verbose_name="active"),
        ),
        migrations.CreateModel(
            name="BannerEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="created on"),
                ),
                ("result", models.TextField(max_length=1000, verbose_name="result")),
                ("crns", models.TextField(max_length=100, verbose_name="crns")),
                ("term", models.IntegerField(verbose_name="term")),
                (
                    "banner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notifier.banner",
                        verbose_name="banner",
                    ),
                ),
            ],
            options={
                "verbose_name": "banner event",
                "verbose_name_plural": "banner events",
            },
        ),
    ]
