# Generated by Django 4.2.16 on 2025-08-13 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notifier", "0022_alter_bannerevent_result"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trackinglist",
            name="courses",
        ),
        migrations.RemoveField(
            model_name="trackinglist",
            name="register_courses",
        ),
        migrations.CreateModel(
            name="RegisterCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strategy",
                    models.SmallIntegerField(
                        choices=[
                            (0, "off"),
                            (1, "default"),
                            (2, "linked lab"),
                            (3, "replace with "),
                        ],
                        default=0,
                        verbose_name="strategy",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(auto_now=True, verbose_name="updated on"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notifier.course",
                        verbose_name="course",
                    ),
                ),
                (
                    "tracking_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notifier.trackinglist",
                        verbose_name="tracking list",
                    ),
                ),
                (
                    "with_add",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="notifier.course",
                        verbose_name="with add course",
                    ),
                ),
                (
                    "with_drop",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="notifier.course",
                        verbose_name="with drop course",
                    ),
                ),
            ],
            options={
                "verbose_name": "register course",
                "verbose_name_plural": "register courses",
            },
        ),
        migrations.AddConstraint(
            model_name="registercourse",
            constraint=models.UniqueConstraint(
                models.F("tracking_list"),
                models.F("course"),
                name="unique_trackinglist_course",
            ),
        ),
    ]
