# Generated by Django 4.2.16 on 2025-08-17 17:40

from django.db import migrations
import django_choices_field.fields
import notifier.models


class Migration(migrations.Migration):

    dependencies = [
        ("notifier", "0023_remove_trackinglist_courses_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registercourse",
            name="strategy",
            field=django_choices_field.fields.IntegerChoicesField(
                choices=[
                    (0, "off"),
                    (1, "default"),
                    (2, "linked lab"),
                    (3, "replace with "),
                ],
                choices_enum=notifier.models.RegisterCourse.RegisterStrategyEnum,
                default=0,
                verbose_name="strategy",
            ),
        ),
    ]
