# Generated by Django 4.1b1 on 2022-07-20 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0012_alter_profile_major'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotUser',
            fields=[
                ('telegram_user_id', models.CharField(default='', max_length=256)),
                ('telegram_username', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='account.profile')),
            ],
        ),
    ]
