# Generated by Django 4.0.6 on 2022-07-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramprofile',
            name='telegram_user_id',
            field=models.CharField(max_length=256, unique=True, verbose_name='telegram user ID'),
        ),
        migrations.AlterField(
            model_name='telegramprofile',
            name='telegram_username',
            field=models.CharField(max_length=256, unique=True, verbose_name='telegram username'),
        ),
    ]
