# Generated by Django 4.0.6 on 2022-07-22 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import telegram_bot.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telegram_bot', '0002_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default=telegram_bot.models.generate_token_str, help_text='random generated', max_length=5, verbose_name='token'),
        ),
        migrations.AlterField(
            model_name='token',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
