# Generated by Django 4.0.6 on 2022-07-22 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'ordering': ['-created_on', 'user'], 'verbose_name': 'token', 'verbose_name_plural': 'tokens'},
        ),
    ]
