# Generated by Django 4.0.6 on 2022-07-22 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telegram_bot', '0002_remove_telegramprofile_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_profile', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
