# Generated by Django 4.0.6 on 2022-08-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0003_alter_telegramprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramprofile',
            name='username',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='telegram username'),
        ),
    ]
