# Generated by Django 4.0.6 on 2022-08-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0004_alter_telegramprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramprofile',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='telegram user ID'),
        ),
    ]
