# Generated by Django 3.2.2 on 2021-06-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('major', models.TextField()),
                ('course', models.TextField()),
                ('report', models.IntegerField()),
            ],
        ),
    ]
