# Generated by Django 3.2.2 on 2021-06-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='report',
            field=models.IntegerField(default=0),
        ),
    ]
