# Generated by Django 3.2.2 on 2021-06-21 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('whatsapp', '0002_auto_20210617_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='group',
            name='course',
            field=models.TextField(verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='group',
            name='link',
            field=models.URLField(verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='group',
            name='major',
            field=models.TextField(verbose_name='Major'),
        ),
        migrations.AlterField(
            model_name='group',
            name='report',
            field=models.IntegerField(default=0, verbose_name='Report'),
        ),
        migrations.AlterField(
            model_name='group',
            name='verified',
            field=models.BooleanField(default=True, verbose_name='Verified'),
        ),
    ]
