# Generated by Django 3.2.2 on 2021-06-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_auto_20210621_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='course',
            field=models.CharField(max_length=10, verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='group',
            name='major',
            field=models.CharField(max_length=10, verbose_name='Major'),
        ),
    ]
