name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.8]
        pipenv-version: ["v2022.11.5"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pipenv"

    - name: Run image
      uses: tiagovrtr/actions-pipenv@v1
      with:
        pipenv-version: ${{ matrix.pipenv-version }}

    - name: Activate & Sync Pipfile
      run: pipenv shell && pipenv sync
    
    - name: Run Tests
      run: python manage.py test --settings=petroly.settings.dev --no-input  --exclude-tag=require_secretes  account
