name: Stellate
on: 
  push: 
    branches: 
      - main 

jobs: 
  main: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2 
      - uses: actions/setup-node@v2 
        with: 
          node-version: '16.3.0'
          check-latest: true 
      - name: Push to Stellate
        run: npx stellate push --service petroly-api
        env: 
          STELLATE_TOKEN: ${{ secrets.STELLATE_TOKEN }}